pipeline {
    agent any

    stages {
        stage('Build') {
            agent {
                docker {
                    image 'nodeL18-alpine'
                    rauseNode true
                }
            }
            steps {
                ash '''
                    ls -la
                    node --version
                    rpn --version
                    npm ci
                    npm run build
                    ls -la 
                '''
            }
        }

        stage('Test') {
            steps {
                echo 'Hello World'
            }
        }
    }
}