pipeline {
    agent any

    stages {
        stage('Build') {
            agent {
                docker {
                    image 'node:18-alpine'
                    reuseNode true
                }
            }
            steps {
                script {
                    def nodeInstalled = sh(script: 'which node || true', returnStdout: true).trim()
                    if (nodeInstalled) {
                        sh '''
                            ls -la
                            node --version
                            npm --version
                            npm ci
                            npm run build
                            ls -la
                        '''
                    } else {
                        sh '''
                            sudo dnf install nodejs npm -y
                        '''
                        error 'Node.js was not installed. Please re-run the pipeline.'
                    }
                }
               
            }
        }
    }
}